### ISSUE TITLE
Hello, what type of GPU are you using for training, what is the number, and how long do you need to train?

### ISSUE THREAD

**Issue by SUNziwei0527** [Zhicaiwww/Bi-VAEGAN#1]
Hello, what type of GPU are you using for training, what is the number, and how long do you need to train?

**Comment by Zhicaiwww** [comment]
We use a single RTX 3090 for training for about 2~5 hours depending on the datasets and corresponding epochs. Generally, it will take a little more time than F-VAEGAN since we additionally train the regressor.

**Comment by Zhicaiwww** [comment]
@SUNziwei0527 We use a single RTX 3090 for training for about 2~5 hours depending on the datasets and corresponding epochs. Generally, it will take a little more time than F-VAEGAN since we additionally train the regressor.
