### ISSUE TITLE
How to perform the transductive training process after obtaining "class prior"?

### ISSUE THREAD

**Issue by long-wa** [Zhicaiwww/Bi-VAEGAN#4]
Hello, dear author, I have observed an inconsistency within your code implementation. Specifically, there appears to be an omission in which the conversion of the parameter "opt.transductive" to True is not executed subsequent to obtaining the "class_prior". Consequently, I am uncertain as to how Step 13 of Algorithm 1, as described in the word, is achieved. This implies that the code fails to execute the transductive training process subsequent to obtaining the "class_prior".

**Comment by Zhicaiwww** [comment]
Thank you for pointing out the issues in the code. I have now corrected the bugs in the code based on your feedback. Please review the updated code, which now allows the use of the class prior estimated during inductive training to assist with transductive training.

**Comment by long-wa** [comment]
Received, dear author, thank you very much for your very meaningful work.O(∩_∩)O
