### ISSUE TITLE
Can you explain how certain parameters in the script are tuned?

### ISSUE THREAD

**Issue by Anduin9527** [Zhicaiwww/Bi-VAEGAN#8]
Hi, I'm a newbie here. I am trying to apply your findings to my own dataset with about 800 samples. But the question is: I noticed that you adjusted the parameters gamma, SYN_NUM, BETA and encoded_noise for different datasets, can you share some tips for adjusting the parameters?

**Comment by Zhicaiwww** [comment]
Generally, the learning rate and radius $r$ play the most important role here.
- The learning rate is highly dataset-dependent.
- The radius $r$ could be set as 1, or larger (for some datasets, 3 or 5 will reach the best performance).
- Gamma is a sensitive term that determines the training of GAN. Choose the default values from CUB, and if the training doesn't converge, you may need to adjust it (always remember that the generator should have a smaller gamma than the discriminator).
- 'encoded_noise' is the least important term.
- For SYN_NUM, it will be enough to set it as 10 times the number of averaged samples for each class.

**Comment by Anduin9527** [comment]
Thank you for your patience and your amazing work🫡
